/**
 * File:        eslint.config.mjs
 * Authors:     Roni Amiel & Eden Bitran
 * Description: ESLint flat configuration. Extends the Next.js presets and
 *              excludes generated and vendored output — linting code we did
 *              not write produces noise that trains you to ignore the linter.
 * Version:     0.3.0
 *
 * Modifications:
 *     0.2.0 - 2026-08-03 - Generated by create-next-app (Phase 0.5)
 *     0.3.0 - 2026-08-03 - Ignore the Supabase CLI cache, generated database
 *                          types and test artefacts (Phase 1a)
 */

import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",

    // Supabase CLI working directories. `.temp` holds container scratch files,
    // including a minified edge-runtime bundle that produces ~150 bogus errors.
    "supabase/.temp/**",
    "supabase/.branches/**",

    // Written by `npm run gen:types`; hand-edits there are always a mistake.
    "src/types/database.types.ts",

    // Test and coverage output.
    "playwright-report/**",
    "test-results/**",
    "coverage/**",
  ]),
]);

export default eslintConfig;
