/**
 * File:        next.config.ts
 * Authors:     Roni Amiel & Eden Bitran
 * Description: Next.js configuration.
 * Version:     0.7.1
 *
 * Modifications:
 *     0.2.0 - 2026-08-03 - Generated by create-next-app (Phase 0.5)
 *     0.7.1 - 2026-08-05 - Raise the server action body limit so avatar
 *                          uploads are not rejected at 1 MB
 */

import type { NextConfig } from 'next';

const nextConfig: NextConfig = {
  experimental: {
    serverActions: {
      /*
       * Server actions default to a 1 MB request body, which the avatar upload
       * exceeded — the file is posted through the action rather than straight
       * to Storage, so the whole image counts against this limit.
       *
       * 5 MB, not 2 MB, even though the storage bucket caps files at 2 MB. The
       * limit here applies to the ENTIRE multipart body: the image plus every
       * other field on the form plus multipart overhead. Setting it to the file
       * size would reject a 2 MB photo that is otherwise perfectly valid. The
       * real size rule stays where it belongs — checked in the action and
       * enforced again by the bucket.
       */
      bodySizeLimit: '5mb',
    },
  },
};

export default nextConfig;
